// <auto-generated />
using System;
using MainWebGame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MainWebGame.Migrations
{
    [DbContext(typeof(ScoreModelContext))]
    partial class ScoreModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MainWebGame.Models.PeraturanModel", b =>
                {
                    b.Property<int>("IdPeraturan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdPeraturan");

                    b.ToTable("Peraturan");
                });

            modelBuilder.Entity("MainWebGame.Models.Riwayat", b =>
                {
                    b.Property<int>("IdRiwayat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ai")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Akhir")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Awal")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IdTantangan")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdRiwayat");

                    b.ToTable("Riwayat");
                });

            modelBuilder.Entity("MainWebGame.Models.ScoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Lost")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Win")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("MainWebGame.Models.Tantangan", b =>
                {
                    b.Property<int>("IdTantangan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LawanId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("LawanScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserScore")
                        .HasColumnType("int");

                    b.HasKey("IdTantangan");

                    b.ToTable("Tantangan");
                });
#pragma warning restore 612, 618
        }
    }
}
